mrz_sso:
  db:
    sql:
      production:
        hostname: hostname:port
        username: username_db
        password: password_db
        db_name: db_name
  security:
    salt: 1234567890abcdef1234567890abcdef
    http_auth_users:
      - username: username
        password: passwd
    mgmt_auth_users:
      - username: username
        password: passwd
